title: Introduction to Deep Learning
logo: /assets/img/logo.gif
description: Tuesday August 10th, 2021 (8:00am - 11:00am PCT) & Wednesday August 11th, 2021 (8:00am - 11:00am PCT)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
