title: Intermediate Topics in Machine Learning and Deep Learning
logo: /assets/img/logo.gif
description: Monday August 16th, 2021 (8:00am - 11:00am PT) & Tuesday August 17th, 2021 (8:00am - 11:00am PT)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
